[WIP] Improvements to World related stuff
LegacyRewoven/yarn pull request #1
Opened 2021-12-22 18:48 UTC by PseudoDistant

I'm going to work on this more, it's not done yet.

2021-12-22 18:49 UTC, PseudoDistant commented
OH MY GOD THE CHECKS!

2021-12-24 16:06 UTC, arthurbambou commented
Check failed because you created a conflict.

net/minecraft/class_794/getOrGenerateChunk
And
net/minecraft/class_476/loadChunk

Must have the same name, because they have the same intermediary name.

2021-12-24 16:07 UTC, arthurbambou commented
ChunkProvider and ClientChunkProvider

2021-12-25 15:52 UTC, PseudoDistant commented
> Check failed because you created a conflict.
> 
> net/minecraft/class_794/getOrGenerateChunk And net/minecraft/class_476/loadChunk
> 
> Must have the same name, because they have the same intermediary name.

thonk

2021-12-25 15:56 UTC, PseudoDistant commented
![Screenshot_20211225_105423](https://user-images.githubusercontent.com/67613281/147388848-8180b4c6-6b1f-47c8-8bdb-2d827e37f9f6.png)

2021-12-25 15:57 UTC, PseudoDistant commented
![Screenshot_20211225_105710](https://user-images.githubusercontent.com/67613281/147388867-dd251a7e-a8a7-443c-a93f-57fa8a127590.png)

Cursed

2021-12-25 16:57 UTC, arthurbambou approved these changes

2021-12-25 17:23 UTC, PseudoDistant commented
I'm still not done with this, there's still more to map.

2021-12-25 19:55 UTC, arthurbambou requested changes

2021-12-25 19:55 UTC, arthurbambou commented on mappings/net/minecraft/world/biome/Biome.mapping
> +	FIELD field_12450 biomeRegistry Lnet/minecraft/class_1943;
```suggestion
	FIELD field_12450 REGISTRY Lnet/minecraft/class_1943;
```

2021-12-25 20:13 UTC, PseudoDistant commented
How does this all look?
Like should there be more work put into somewhere or can this be merged in?
(I can work more in a future PR, but I'd like to get a few of these changes in very soon.)

2021-12-25 20:20 UTC, PseudoDistant commented on mappings/net/minecraft/world/biome/Biome.mapping
> +	FIELD field_12450 biomeRegistry Lnet/minecraft/class_1943;
Merged. :>

2021-12-25 20:35 UTC, PseudoDistant commented
May as well rename this.

2021-12-25 21:29 UTC, arthurbambou approved these changes

2021-12-26 01:51 UTC, BluCobalt approved these changes

2021-12-26 06:21 UTC, PseudoDistant commented
@BoogieMonster1O1 AAAAAAAAAAAAAA

2021-12-26 06:25 UTC, BoogieMonster1O1 approved these changes

2021-12-26 06:25 UTC, merged